### ISSUE TITLE
Merge Edge branch into Next-Release?

### ISSUE THREAD

**Issue by GQAssurance** [Omenia/webdrivermanager#10]
Hi Rasjani!   I am curious if you plan to bring in your edge branch into next release?

Just curious, that's all!

We stopped using this library for now (instead have a docker image with drivers installed) ... but I know this is a valuable project!

**Comment by rasjani** [comment]
Yes.  It is coming soon - most likely this week. There are few bugs still left in that i need to address and 0.7 after i fixed those.

**Comment by rasjani** [comment]
If you want to take the next version for a spin (and report back any possible bugs you find), you can get the pre-release from test pypi via:

pip install --index-url https://test.pypi.org/simple/  --extra-index-url https://pypi.org/simple  webdrivermanager==0.7.0

**Comment by rasjani** [comment]
fixed in 0.7.1
