### ISSUE TITLE
ModuleNotFoundError: No module named 'version'

### ISSUE THREAD

**Issue by quarckster** [Omenia/webdrivermanager#16]
This line https://github.com/Omenia/webdrivermanager/blob/master/webdrivermanager/cli.py#L7 breaks webdrivermanager in Python 3.6

https://travis-ci.org/quarckster/widgetastic.patternfly4/jobs/505817094#L568

**Comment by rasjani** [comment]
For future reference, this seems to be related to pyenv.

**Comment by quarckster** [comment]
It's not related to pyenv. In python 3 you have to use absolute imports like this:
```python
from webdrivermanger.version import get_version
```
or you can use relative import:
```python
from .version import get_version
```
